---
- name: ssh_hardening | ensure fail2ban is installed
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: ssh_hardening | deploy jail.local
  ansible.builtin.template:
    src: fail2ban_jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: ssh_hardening | restart fail2ban

- name: ssh_hardening | ensure fail2ban is enabled and running
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
